### ISSUE TITLE
Stop using normalize.css

### ISSUE THREAD

**Issue by lifeiscontent** [jquery/css-chassis#92]
since you guys are interested in browser testing. Why not write your own "normalize.css"

I've always found myself finding normalize being more of a pain than a solution when building http://fortitude.io I actually wanted to spend some time writing a test harness that would tell me the default styles of every element for every browser and normalize the properties based off actual concrete values from the browsers and not from a human, though the human who wrote normalize is a very smart person, he is indeed only human.

What do you guys think of this approach?

**Comment by fskreuz** [comment]
Throwing in ideas (correct me if I'm wrong, I might be a bit outdated with the hype):

- You can diff screenshots against a known template using the following headless engines:
    - PhantomJS has screen capture capability: http://phantomjs.org/screen-capture.html
    - SlimerJS also has screen capture capability: https://docs.slimerjs.org/current/quick-start.html
    - CasperJS does both engines, also has capture capability: http://docs.casperjs.org/en/latest/modules/casper.html#capture
- A service in beta called https://percy.io/ has the same diffing functionality, but is limited to Firefox.

The image diff can then be analyzed and corrections can then be made. The diffing tool can also be made to provide suggestions or even automate corrections. Diffing is also possible using canvas (trust me, I've done it :P) so we can script PhantomJS to do it and be purely web (goodby OpenCV).

Now the problem of all of these, they only run on specific versions of the engines. Not sure (haven't checked) if the commercial solutions out there can do the same thing as percy (otherwise, why was percy built anyways?) or if they provide screenies for each browser in their army.

As long as a minimum of providing a screenshot for a browser is possible, diffing it won't be an issue.
